# # Uncomment the next line to define a global platform for your project
# # platform :ios, '9.0'
#
# target 'Runner' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!
#
#   # Pods for Runner
#    pod 'Firebase/Core'
#    pod 'Firebase/Analytics'
#    pod 'Firebase/Auth'
#    pod 'Firebase/Firestore'
#
#   target 'RunnerTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
#
# end
platform :ios, '10.0'

# CocoaPods analytics: https://cocoapods.org/analytics
install! 'cocoapods', :deterministic_uuids => false

target 'Runner' do
  use_frameworks!

  # Flutter dependencies
  flutter_application_path = '../'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

  # Add Firebase pods
  pod 'Firebase/Core', '~> 3.2.0' # Make sure the version matches the Firebase version you need
  pod 'Firebase/Analytics', '~> 11.2.1'
  pod 'Firebase/Auth', '~> 5.1.2'
  pod 'Firebase/Firestore', '~> 5.1.0'
  pod 'Firebase/Storage', '~> 12.1.3'
  pod 'Firebase/AppCheck', '~> 0.3.0+4' # Check the latest version compatibility

  # Add other necessary pods
  pod 'Provider', '~> 6.1.2'
  pod 'ImagePicker', '~> 1.1.2'
  pod 'HTTP', '~> 1.2.2'
  pod 'FlutterSpinKit', '~> 5.2.1'
  pod 'PlayIntegrityFlutter', '~> 0.0.1'
  pod 'AppIntegrityChecker', '~> 1.0.5'
  pod 'CountryCodePicker', '~> 3.0.0'
  pod 'IntlPhoneField', '~> 3.2.0'
  pod 'LocalAuth', '~> 2.3.0'
  pod 'SharedPreferences', '~> 2.3.2'

  # Ensure the Firebase pods are included
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
